#!/bin/bash

case "${1}" in
    configure)
        echo Setting up symbolic link to assemblies ...
	ln -s /opt/mono/lib /opt/mono/bin/nubian-demo/nubianbin
		;;

    abort-remove)
	echo Removing symbolic link to aasemblies
	rm -r /opt/mono/bin/nubian-demo/nubianbin
        ;;

    abort-upgrade)
        ;;
    *)
        echo "postinst called with unknown argument (${1})"
        exit 1
        ;;
esac

exit 0
