#!/bin/bash

case "${1}" in
    remove|deconfigure)
        echo Removing symbolic links to assemblies...
	rm -r /opt/mono/bin/nubian-demo/nubianbin
        ;;

    upgrade)
        ;;

    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument (${1})"
        exit 1
        ;;
esac

exit 0
