#!/bin/bash

case "${1}" in
    configure)
        echo Registering in GAC ...
        gacutil -i /tmp/nubian/nubian.MonoRuntimeResolver.dll
		;;

    abort-remove)
        ;;

    abort-upgrade)
        ;;
    *)
        echo "preinst called with unknown argument (${1})"
        exit 1
        ;;
esac

exit 0
