#!/bin/bash

case "${1}" in
    configure)
        echo Registering in GAC ...
        gacutil -i /opt/nubian/gacd/nubian/nubian.MonoRuntimeResolver.dll
		;;

    abort-remove)
        gacutil -u nubian.MonoRuntimeResolver.dll
        ;;

    abort-upgrade)
        gacutil -u nubian.MonoRuntimeResolver.dll
        ;;
    *)
        echo "postinst called with unknown argument (${1})"
        exit 1
        ;;
esac

exit 0
