#!/bin/bash

case "${1}" in
    remove|deconfigure)
        echo Removing Mono Assembly Resolver from GAC...
        gacutil -u nubian.MonoRuntimeResolver
        ;;

    upgrade)
        ;;

    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument (${1})"
        exit 1
        ;;
esac

exit 0
