#!/bin/bash

case "${1}" in
    remove|deconfigure)
        echo Configuring Mono Assembly Resolver ...
        gacutil -u nubian.MonoRuntimeResolver.dll
        ;;

    upgrade)
        ;;

    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument (${1})"
        exit 1
        ;;
esac

exit 0
